### ISSUE TITLE
JsonObject mergeIn function lost value 

### ISSUE THREAD

**Issue by AlexanderBurykin** [eclipse/vert.x#1283] opened 2016-01-18 05:54 UTC
mergeIn function overwrite previos value of JsonObject.
for example:
JsonObject origin = new JsonObject().put("key", new JsonObject("foo","bar"));
origin.mergeIn(new JsonObject().put("key", new JsonObject("fooo","barr")));

outputs:
  {"key":{"fooo": "barr"}}

instead of expected output:
  {"key":{"foo": "bar", "fooo": "barr"}}

**Comment by davidafsilva** [comment] 2016-01-18 08:57
I believe that is by design. According to the API:
`This is the equivalent of putting all the entries of the other JSON object into this object.`
So, it replaces all the root entries that conflict, hence you'll get the key from the object you are merging from.

**Comment by vietj** [comment] 2016-01-18 09:17
agreed with you, it's an an deep merge that happens, only top level, I'm closing this.

**Closed by vietj** 2016-01-18 09:17 UTC
