### ISSUE TITLE
Vertx Deadlock:  ServerConnection.handleClosed() v. SockJSSession.write()

### ISSUE THREAD

**Issue by mordant628** [eclipse/vert.x#1739] opened 2016-12-12 18:45 UTC
This deadlock is happening on v3.2.1, however it appears that the same lock inversion problem exists on the current v3.3.3.   I will be trying to created a tiny, canned example to repro this soon, but because it involves a 'channel inactive' call I'm thinking this is far more of a timing issue instead of a connection/load issue.  

Also, all locking here is OUTSIDE of our 'acme' code, and inside the vertx codebase.  From my understanding of these stack traces and the threading model, this essentially means that any SockJSSession.write() call (regardless of the thread it is called from) can deadlock with a 'ServerConnection.handleClose()' call.  

some package names have been changed to 'acme' to protect the innocent:

`
2016-12-09 18:45:36
Full thread dump OpenJDK 64-Bit Server VM (25.111-b15 mixed mode):
....
Found one Java-level deadlock:
=============================
"vert.x-eventloop-thread-6":
  waiting to lock monitor 0x00007fe2566ab5d8 (object 0x0000000793370080, a io.vertx.ext.web.handler.sockjs.impl.SockJSSession),
  which is held by "vert.x-eventloop-thread-4"
"vert.x-eventloop-thread-4":
  waiting to lock monitor 0x00007fe20dc395f8 (object 0x000000076fa3d330, a io.vertx.core.http.impl.ServerConnection),
  which is held by "vert.x-eventloop-thread-6"

Java stack information for the threads listed above:
===================================================
"vert.x-eventloop-thread-6":
	at io.vertx.ext.web.handler.sockjs.impl.SockJSSession.shutdown(SockJSSession.java:179)
	- waiting to lock <0x0000000793370080> (a io.vertx.ext.web.handler.sockjs.impl.SockJSSession)
	at io.vertx.ext.web.handler.sockjs.impl.BaseTransport$BaseListener$1.handle(BaseTransport.java:124)
	at io.vertx.core.VoidHandler.handle(VoidHandler.java:27)
	at io.vertx.core.VoidHandler.handle(VoidHandler.java:24)
	at io.vertx.core.http.impl.HttpServerResponseImpl.handleClosed(HttpServerResponseImpl.java:554)
	- locked <0x000000076fa3d330> (a io.vertx.core.http.impl.ServerConnection)
	at io.vertx.core.http.impl.ServerConnection.handleClosed(ServerConnection.java:341)
	- locked <0x000000076fa3d330> (a io.vertx.core.http.impl.ServerConnection)
	at io.vertx.core.net.impl.VertxHandler$$Lambda$72/866006627.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl$$Lambda$14/2028784198.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:218)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:204)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:218)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:204)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:625)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
"vert.x-eventloop-thread-4":
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:153)
	- waiting to lock <0x000000076fa3d330> (a io.vertx.core.http.impl.ServerConnection)
	at io.vertx.core.http.impl.HttpServerResponseImpl.putHeader(HttpServerResponseImpl.java:52)
	at io.vertx.ext.web.handler.sockjs.impl.BaseTransport.setJSESSIONID(BaseTransport.java:158)
	at io.vertx.ext.web.handler.sockjs.impl.XhrTransport$BaseXhrListener.sendFrame(XhrTransport.java:149)
	at io.vertx.ext.web.handler.sockjs.impl.XhrTransport$XhrPollingListener.sendFrame(XhrTransport.java:168)
	at io.vertx.ext.web.handler.sockjs.impl.SockJSSession.writePendingMessages(SockJSSession.java:249)
	- eliminated <0x0000000793370080> (a io.vertx.ext.web.handler.sockjs.impl.SockJSSession)
	at io.vertx.ext.web.handler.sockjs.impl.SockJSSession.write(SockJSSession.java:117)
	- locked <0x0000000793370080> (a io.vertx.ext.web.handler.sockjs.impl.SockJSSession)
	at acme.collab.FooEventBusBridgeImpl.deliverMessage(FooEventBusBridgeImpl.java:323)
	at acme.collab.FooEventBusBridgeImpl.lambda$null$9(FooEventBusBridgeImpl.java:212)
	at acme.collab.FooEventBusBridgeImpl$$Lambda$107/1190021858.handle(Unknown Source)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handleMessage(HandlerRegistration.java:207)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:201)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$127(EventBusImpl.java:498)
	at io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$117/2085642535.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
	at io.vertx.core.impl.ContextImpl$$Lambda$14/2028784198.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.

Heap
 PSYoungGen      total 2024960K, used 1730703K [0x0000000717580000, 0x0000000799900000, 0x00000007c0000000)
  eden space 1916416K, 86% used [0x0000000717580000,0x000000077ce193e8,0x000000078c500000)
  from space 108544K, 61% used [0x0000000792f00000,0x000000079708aad8,0x0000000799900000)
  to   space 108544K, 0% used [0x000000078c500000,0x000000078c500000,0x0000000792f00000)
 ParOldGen       total 5527040K, used 188936K [0x00000005c6000000, 0x0000000717580000, 0x0000000717580000)
  object space 5527040K, 3% used [0x00000005c6000000,0x00000005d1882148,0x0000000717580000)
 Metaspace       used 57781K, capacity 58830K, committed 59284K, reserved 1101824K
  class space    used 6771K, capacity 6989K, committed 7060K, reserved 1048576K
`

The only options we see right now to work around this are either (A) reducing the eventloop threadpool size to one, or (B) somehow acquiring and synchronizing on the appropriate ServerConnection instance BEFORE we make a SockJSSession.write() call.  This option (B) must be done before all calls to 'synchronized' SockJSSession methods, not just .write().  

The  'bus bridge impl' that we are using is based on the impl at:

  https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java

with minor modifications to support a 'PING' socket data message type.  The ping support just pokes some bean internal state, doesn't do any other socket read/write calls, and it independent of the above stack trace.

rfc.

**Comment by mordant628** [comment] 2016-12-12 19:05
fwiw, here are a few similar-but-different issues:

* https://github.com/eclipse/vert.x/issues/1466
* https://github.com/vert-x3/vertx-web/issues/344
* https://github.com/vert-x3/vertx-web/issues/310#

And this one fixed in v3.3.0 also appears to be different:
* https://github.com/eclipse/vert.x/issues/1247

The offending synchronization code for the SockJSSession.java, ServerConnection.java, and HttpServerResponseImpl.java also looks to be the same between v3.1.0 and v3.3.3, so this bug may have been lurking for a while?

**Comment by vietj** [comment] 2016-12-13 07:12
looking forward for the reproducer @mordant628

**Comment by mordant628** [comment] 2016-12-14 22:47
@vietj 

I present you the gift of a vertx deadlock (aka, vxdl) producer for your very merry holiday season, demonstrating the existence of a classic lock inversion bug:

   https://github.com/mordant628/vxdl

I hope you can deal with a maven project.   At the root of that repo there is a 'deadlock.sh' program which:

1.  starts up two different consumers of the eventbus eventsource stream
2.  registers both streams for a pub/sub address
3.  sends a message to the registered address, triggering some artificial Thread.sleep() code to induce the deadlock
4.  kills both event stream consumers while eventloop threads are in the Thread.sleep() states.  This triggers a DefaultChannelPipeline.fireChannelInactive() call which causes a
5.  deadlock.

There is still some thread scheduling indeterminism in this deadlock.sh code, but I'm still getting it to reproduce about 50% of the time.   So if you run it without seeing the deadlock, then just run it again and you should see the deadlock from the jvm SIGQUIT stacktrace dump.

Of note:
*  The vxdl.DeadlockEventBusBridgeImpl.java class is essentially a direct copy from:  https://raw.githubusercontent.com/vert-x3/vertx-web/master/vertx-web/src/main/java/io/vertx/ext/web/handler/sockjs/impl/EventBusBridgeImpl.java
*  This vxdl.DeadlockEventBusBridgeImpl.java has a single modification around line 371 which passes in a custom Buffer.java implementation.  This custom SleepyBuffer.java implementation simply injects some Thread.sleep() calls to artificially induce the deadlock, thereby allowing other threads to run AFTER the sock.write() method has already synchronized at the method level.
* I also had to drag in a copy of the BridgeEventImpl.java class from the same vert-x3 codebase; the official vert-x3 one is package protected and therefore invisible to the DeadlockEventBusBridgeImpl copy.
* As far as I can tell all other code is pretty much stock, standard, and conventional spring code for starting and wiring up the verticles, beans, routes, etc.  It is all essentially copied and distilled from our production code.


And just for completeness, here is an example deadlock from this vxdl project:

`
Found one Java-level deadlock:
=============================
"vert.x-eventloop-thread-6":
  waiting to lock monitor 0x00007fd3c0239c58 (object 0x000000076f7b10b0, a io.vertx.core.http.impl.ServerConnection),
  which is held by "vert.x-eventloop-thread-4"
"vert.x-eventloop-thread-4":
  waiting to lock monitor 0x00007fd3c0005038 (object 0x0000000781b6f860, a io.vertx.ext.web.handler.sockjs.impl.SockJSSession),
  which is held by "vert.x-eventloop-thread-6"

Java stack information for the threads listed above:
===================================================
"vert.x-eventloop-thread-6":
        at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:584)
        - waiting to lock <0x000000076f7b10b0> (a io.vertx.core.http.impl.ServerConnection)
        at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:271)
        at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:52)
        at io.vertx.ext.web.handler.sockjs.impl.EventSourceTransport$EventSourceListener.sendFrame(EventSourceTransport.java:99)
        at io.vertx.ext.web.handler.sockjs.impl.SockJSSession.writePendingMessages(SockJSSession.java:249)
        - locked <0x0000000781b6f860> (a io.vertx.ext.web.handler.sockjs.impl.SockJSSession)
        at io.vertx.ext.web.handler.sockjs.impl.SockJSSession.write(SockJSSession.java:117)
        - locked <0x0000000781b6f860> (a io.vertx.ext.web.handler.sockjs.impl.SockJSSession)
        at vxdl.DeadlockEventBusBridgeImpl.lambda$deliverMessage$22(DeadlockEventBusBridgeImpl.java:371)
        at vxdl.DeadlockEventBusBridgeImpl$$Lambda$114/1103867689.run(Unknown Source)
        at vxdl.DeadlockEventBusBridgeImpl.lambda$checkCallHook$3(DeadlockEventBusBridgeImpl.java:179)
        at vxdl.DeadlockEventBusBridgeImpl$$Lambda$91/1819590866.handle(Unknown Source)
        at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
        at vxdl.DeadlockEventBusBridgeImpl.checkCallHook(DeadlockEventBusBridgeImpl.java:175)
        at vxdl.DeadlockEventBusBridgeImpl.deliverMessage(DeadlockEventBusBridgeImpl.java:370)
        at vxdl.DeadlockEventBusBridgeImpl.lambda$null$9(DeadlockEventBusBridgeImpl.java:257)
        at vxdl.DeadlockEventBusBridgeImpl$$Lambda$104/961587176.handle(Unknown Source)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handleMessage(HandlerRegistration.java:207)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:201)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$127(EventBusImpl.java:498)
        at io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$111/339356144.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
        at io.vertx.core.impl.ContextImpl$$Lambda$13/1527447753.run(Unknown Source)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
"vert.x-eventloop-thread-4":
        at io.vertx.ext.web.handler.sockjs.impl.SockJSSession.shutdown(SockJSSession.java:179)
        - waiting to lock <0x0000000781b6f860> (a io.vertx.ext.web.handler.sockjs.impl.SockJSSession)
        at io.vertx.ext.web.handler.sockjs.impl.BaseTransport$BaseListener$1.handle(BaseTransport.java:124)
        at io.vertx.core.VoidHandler.handle(VoidHandler.java:27)
        at io.vertx.core.VoidHandler.handle(VoidHandler.java:24)
        at io.vertx.core.http.impl.HttpServerResponseImpl.handleClosed(HttpServerResponseImpl.java:554)
        - locked <0x000000076f7b10b0> (a io.vertx.core.http.impl.ServerConnection)
        at io.vertx.core.http.impl.ServerConnection.handleClosed(ServerConnection.java:341)
        - locked <0x000000076f7b10b0> (a io.vertx.core.http.impl.ServerConnection)
        at io.vertx.core.net.impl.VertxHandler$$Lambda$73/497689988.run(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:333)
        at io.vertx.core.impl.ContextImpl$$Lambda$13/1527447753.run(Unknown Source)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
        at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:218)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:204)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:332)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:218)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:204)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:625)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.

`

**Comment by vietj** [comment] 2016-12-15 07:53
thanks

I believe that the deadlock has been identified for a while (cf issue tracker in vertx-web), my advocated solution is to use a single lock that sockjs would obtain from the http connection or reorder some operations to use the event loop

**Comment by vietj** [comment] 2016-12-15 20:20
so your reproducer needs to modify existing vertx classes ?

**Comment by vietj** [comment] 2016-12-15 21:13
actually got it when running several times

**Comment by vietj** [comment] 2016-12-15 21:48
are you observing this behavior on a real use case ?

**Comment by vietj** [comment] 2016-12-15 21:53
this https://gist.github.com/vietj/05e157a7871552d40e826e0e48e1be65 should eliminate the problem you are seing - I will open an issue in Vert.x Web for properly handling it.

**Comment by sdmuffat** [comment] 2016-12-15 21:56
yes, it's happening in production.  I think it's roughly once or twice a week.

**Comment by vietj** [comment] 2016-12-15 22:01
I opened this issue https://github.com/vert-x3/vertx-web/issues/501 and I will close this one

**Comment by vietj** [comment] 2016-12-15 22:01
I set status to Invalid because it is not on this project.

**Closed by vietj** 2016-12-15 22:01 UTC

**Comment by vietj** [comment] 2016-12-15 22:05
@sdmuffat this happens because of reuse of the same session id over different connections. It could be solved by deploying a single instance of the Verticle (might not be what you want) or disabling the `XhrTransport` (might not be what you want too).

**Comment by mordant628** [comment] 2016-12-15 22:52
@vietj   thanks.   We are implementing that patch of yours in our production code, and I'll ping back if we continue to have this deadlock.

**Comment by vietj** [comment] 2016-12-16 07:25
@mordant628 sure no problem, I believe it *should* be ok but we never know

**Comment by mordant628** [comment] 2017-05-05 19:41
@vietj FWIW, we have been running your fix in production for a month or so now and have not seen this vertx deadlock (or any vertx issues).   Before your fix we would see a deadlock at least once a week, if not once every couple days, so anecdotally it looks like a good patch.

thanks!

**Comment by vietj** [comment] 2017-05-06 06:17
thanks for the feedback @mordant628 !
