### ISSUE TITLE
javax.net.ssl.SSLHandshakeException although setTrustAll is true

### ISSUE THREAD

**Issue by leolux** [eclipse/vert.x#1398] opened 2016-05-03 10:01 UTC
My vertx client cannot connect to an HTTP server via TLS. The server delivers a trusted certificate and the client does not trust the server, because the client connects to the server using "localhost". In my case it works as expected because client and server are running on the same machine and the certificate is trusted for a different domain name (other than "localhost"). Therefore I tried to solve the problem using the easiest solution first:
    httpClientOptions.setTrustAll(true);

But this leads to the following exception:
ERROR [vert.x-worker-thread-15] [i.v.c.http.impl.HttpClientImpl] - javax.net.ssl.SSLHandshakeException: Failed to create SSL connection

I expect that httpClientOptions.setTrustAll(true); makes the client trust both untrusted certificates and trusted certificates which get delivered from a different domain name than the certificate is targeted for.

Yet I haven't tried other solutions like adding the server certificate to the truststore of the client or to change the virtual host file of the OS to simulate that the client connects to a domainserver. (Hint: My router doesn't support NAT Loopbacks). But why does setTrustAll not work as expected?

**Comment by vietj** [comment] 2016-05-03 11:03
Hi, can you provide a reproducer ?

**Comment by leolux** [comment] 2016-05-03 12:04
Should be possible to create a reproducer for this. At the moment I need to find a quick solution. After that I can create a reproducer for this. So It may take some while.

**Comment by vietj** [comment] 2016-05-21 13:28
hi any news from the reproducer ?

**Comment by leolux** [comment] 2016-05-22 11:00
Hi, thank you for the reminder!
There it is: https://github.com/leolux/vertx-ssl-handshake

It reproducdes my issue (throws a SSLHandshakeException) with a self-signed certificate which is targed for the domain *.vertx.io. Neither setTrustAll(true) nor adding the certificate to the truststore prevents this exception. Only changing the virtual host file of the OS and connecting to "any.vertx.io" instead of "localhost" solves the issue.

Does it work as expected. It seems that there is absolutely no chance to make a client trust a certificate which is targeted for a diferent domain.

**Comment by vietj** [comment] 2016-05-23 08:19
Hi,

it is not really possible to do this because the algorithm is not implemented by Vert.x, setTrustAll just acts at the trust verification level.

However there is a work around in Vert.x 3.3 using the new DNS resolver in Vert.x 3.3 (need to use SNAPSHOT for this):

create Vert.x with the following options:

```
    Vertx vertx = Vertx.vertx(new VertxOptions().setHostnameResolverOptions(new HostnameResolverOptions().
        setHostsValue(Buffer.buffer(
            "127.0.0.1       localhost\n" +
            "127.0.0.1       foo.vertx.io"))));
```

and then connect with:

```
      HttpClientRequest request = client.request(HttpMethod.POST, 8888, "foo.vertx.io", "/something", resp -> { ... });
```

The certificate will match foo.vertx.io and the request will succeed.

Is it a solution for you ?

**Comment by vietj** [comment] 2016-05-23 13:08
closing this as it won't be resolved - and there is this mentioned work around for testing.

**Closed by vietj** 2016-05-23 13:08 UTC

**Comment by leolux** [comment] 2016-05-23 19:57
Yes, absolutely! Thanks! 

The new DNS resolver is a great solution for me. It probably comes in handy for all kind of local testing as well.
