### ISSUE TITLE
Lock is not released in clustered vertx

### ISSUE THREAD

**Issue by rogelio-o** [eclipse/vert.x#1521] opened 2016-07-17 18:18 UTC
When I updated the Vertx version, this code stopped working:

```
context.vertx().sharedData().getLock("core.list." + microservice + "." + listId, lockRes -> {
        if(lockRes.failed()) {
                ...
        }
        Lock lock = lockRes.result();
        ...
        lock.release();
});
```

It only executes the code at the first time, but the lock is not released. The execution reaches the release point. What can be the problem?

**Comment by vietj** [comment] 2016-07-17 18:52
what is your cluster manager ?

**Comment by rogelio-o** [comment] 2016-07-17 19:20
Hazelcast. I use it with multicast. But the lock is running only in one node of the cluster. All the other communications mechanisms work fine.

**Comment by rogelio-o** [comment] 2016-07-17 19:32
Recently, I have added metrics with Dropwizard to the project. Can this be a problem?

**Comment by vietj** [comment] 2016-07-22 15:51
can you provide a reproducer ?

**Comment by rogelio-o** [comment] 2016-09-20 09:03
Thanks for your response. I have find out the error. For example, the code below doesn’t work for me:

```
for(int i = 0; i < 10; i++) {
	final int num = i;
	System.out.println(“TRIYING TO GET LOCK " + num);
	vertx.sharedData().getLock("test", lockRes -> {
		if(lockRes.failed()) {
			System.out.println(“LOCK DOESN’T GET  " + num);
		} else {
			System.out.println("GET " + num);
					
			Lock lock = lockRes.result();
					
			context.vertx().setTimer(1000, t -> {
				lock.release();
				System.out.println(“LOCK RELEASED " + num); 
			});
		}
	});
}
```

The problem is the following:
My internal pool for blocking execution only uses 2 workers (even though there are 20 workers in the pool). Hazelcast is synchronous, so the lock is executed in a blocking worker and the worker is “suspended” until we get the lock (the code of how Vertx gets the Hazelcast lock is here: [https://github.com/vert-x3/vertx-hazelcast/blob/master/src/main/java/io/vertx/spi/cluster/hazelcast/HazelcastClusterManager.java] - method getLockWithTimeout).
Then, if we ask for n locks at the same time, we suspend n workers. As you can see in the implementation of HazelcastLock (it is in the same link that was previously mentioned), the lock release is done in a worker too! So, if we want more locks than available workers and the queue execution has to be run in order, lock releases are never executed because they are waiting all the locks are get and the locks are waiting a lock release to get the next. The problem can be solved by executing the release code block without any order (only by adding false in the executeBlocking method):

```
public void release() {
      vertx.executeBlocking(
          (fut) -> {
            semaphore.release();
            fut.complete();
          },
          false,
          (v) -> {
            // Do nothing.
          }
      );
}
```

Thanks for your interesting. I hope this will be helpful for other people with the same problem.

**Comment by tsegismont** [comment] 2017-07-26 15:31
Closing (not a bug)

**Closed by tsegismont** 2017-07-26 15:31 UTC
