### ISSUE TITLE
Metric "vertx.eventbus.messages.pending" can contain incorrect value.

### ISSUE THREAD

**Issue by sfitts** [eclipse/vert.x#1480] opened 2016-06-28 05:34 UTC
Version: 3.3.0

In the case where a handler is removed after a message is sent, but before it is received then the pending count can be incremented, but not decremented.  Consider the following sequence:

A message is delivered locally and a handler is found at line 366 in EventBusImpl.java.  This increments the pending count metric and calls `deliverToHandler`.  When the runOnContext block is scheduled it is determined that the handler has been removed at line 498 and so the message is never actually processed.  As a result the pending count is never decremented making is seem like there are pending messages when in fact there aren't.

This happens most often with the "credit" handler which is installed to receive the credit based flow control messages.  It is often the case that the hander gets removed because the producer has been closed, but the consumer on the other side doesn't know this and sends the credit update.

**Comment by sfitts** [comment] 2016-06-28 05:36
This also results in the message contributing to the "delivered" metric, even though it isn't (though since the % of these is low, that's not as problematic).

**Comment by vietj** [comment] 2016-06-28 12:52
it seems to me that extrapolating a pending count based on these callbacks is not a good idea (although I think it's useful) because a message may not be effectively delivered for the reason you explained but there are other reasons, like a paused MessageConsumer that is unregistered.

**Comment by vietj** [comment] 2016-06-28 13:01
Perhaps that having a callback to signal that a message has been received for a particular handler would be more useful and provide something equivalent :

```
void enqueuedMessage(H handler, boolean local);
```

called in `deliverToHandler` - this would maintain a pending count per handler, that the implementation could handle as it wants. This way the metrics implementation is aware that a message shall be delivered for a particular handler and if that handler is unregistered it can update anything accordingly.

**Comment by vietj** [comment] 2016-06-29 07:22
See : https://github.com/eclipse/vert.x/compare/eventbusmetrics-schedule-message

**Comment by sfitts** [comment] 2016-06-29 14:23
OK, took me a bit to reason out the approach here, but I think it looks good.  Having the pending count is definitely useful since it is the only way to know if messages are getting delayed due to lack of scheduling resources.  Tracking that on a per-handler basis makes sense (since it gives you a more granular picture of which resources are the issue).

Based on this I assume that you'd mark the pending count for the handler in `scheduleMessage` and then adjust in either `beginHandleMessage` or `unregisterHandler`.  You could maintain a global count if you wanted by using state in `HandlerMetric`.  This would also allow for tracking of the time spent waiting to be scheduled.

Thanks for looking at this.

**Comment by vietj** [comment] 2016-06-30 07:50
the schedule message has been implemented and tested for Dropwizard in https://github.com/vert-x3/vertx-dropwizard-metrics/tree/eventbusmetrics-schedule-message

can you have a look and see how it goes for you ?

**Comment by sfitts** [comment] 2016-07-01 03:55
Will do -- I have a newbie question however -- where are the snapshot releases hosted?  I looked in sonatype snapshots and it seems to only have 3.0.0.  Also came up empty poking around the wiki, though I could easily have missed it.  TIA for the help.

**Comment by vietj** [comment] 2016-07-01 06:13
```
    <profile>
      <id>sonatype-repository</id>
      <repositories>
        <repository>
          <id>sonatype-nexus-releases</id>
          <url>https://oss.sonatype.org/content/repositories/releases</url>
          <layout>default</layout>
        </repository>
        <repository>
          <id>sonatype-nexus-snapshots</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
          <layout>default</layout>
          <releases>
            <enabled>false</enabled>
          </releases>
        </repository>
    </repositories>
    </profile>
```

**Comment by vietj** [comment] 2016-07-01 06:14
https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-core/3.3.1-SNAPSHOT/

**Comment by sfitts** [comment] 2016-07-01 06:42
Thanks -- not sure how I missed that.

**Comment by vietj** [comment] 2016-07-04 09:08
hi any feedback ?

**Comment by sfitts** [comment] 2016-07-05 01:33
Sorry -- I'm obviously missing something basic.  I tried this on Thursday, but didn't see the newer code in sonatype, so I figured I'd wait a bit.  Then life intruded so I just tried it again now I and still don't see the new code.  Here is the URL to the sources JAR that I think is current:

https://oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-dropwizard-metrics/3.3.1-SNAPSHOT/vertx-dropwizard-metrics-3.3.1-20160704.234042-13-sources.jar

In my gradle build I have the following:

```
    repositories {
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }
        mavenCentral()
        jcenter()

        // For hadrian analytics
        maven {
            url "http://repository.opendatagroup.com/maven"
        }
```

And I'm able to reference 3.3.1-SNAPSHOT just fine, but I don't see your new code.  Sorry, I know I'm not being much help right now, but I'm not sure what I'm doing wrong.

**Comment by vietj** [comment] 2016-07-05 05:54
hum actually it's not deployed because it's not merged, I'm afraid you should build both yourself.

**Comment by sfitts** [comment] 2016-07-05 15:33
Got it -- failed to notice it was still in a branch.  Unfortunately getting everything built and tested with our server is going to take a bit and I won't have time until after I'm done with some other work stuff.  Walked through the code and it looks good, though I did have one quick question.

Once the code is available in a SNAPSHOT release I can easily give it a try and tell you how it behaves in our environment (for what's the worth).

**Comment by tsegismont** [comment] 2017-07-26 18:01
@sfitts the fix has been released now. Please reopen if there's anything outstanding.

**Closed by tsegismont** 2017-07-26 18:01 UTC

**Comment by dehypnosis** [comment] 2021-07-05 01:48
![image](https://user-images.githubusercontent.com/3263661/124407200-3fbe8380-dd7e-11eb-867e-5bc36e093b8b.png)
Hi, I think it is a similar problem.
In my application, it seems exact number of handlers going up and down well as time goes. while some of pending handlers seem to forget to decrease themselves metric.

**Comment by vietj** [comment] 2021-07-05 09:54
do you have a reproducer for this ?

**Comment by dehypnosis** [comment] 2021-07-07 07:34
@vietj 

Hi, because of company property issue, rather I made a simple code. which creates transient message consumers periodically while providing massive messages into event bus for 10s.

Then I could reproduce the same issue like above. I think this mismatch supposed to happen at the point of unregistering... maybe?

Here is the code:
https://github.com/dehypnosis/vertx-pending-handlers/blob/main/src/main/java/com/kakaomobility/connection/Main.java

And the metrics after message provider stopped, pending handlers not decreasing:
```
# HELP vertx_eventbus_pending Number of messages not processed yet
# TYPE vertx_eventbus_pending gauge
vertx_eventbus_pending{side="local",} 90000.0
# HELP vertx_http_server_active_requests Number of requests being processed
# TYPE vertx_http_server_active_requests gauge
vertx_http_server_active_requests{method="GET",} 1.0
# HELP vertx_http_server_request_bytes_max Size of requests in bytes
# TYPE vertx_http_server_request_bytes_max gauge
vertx_http_server_request_bytes_max{method="GET",} 0.0
# HELP vertx_http_server_request_bytes Size of requests in bytes
# TYPE vertx_http_server_request_bytes summary
vertx_http_server_request_bytes_count{method="GET",} 23.0
vertx_http_server_request_bytes_sum{method="GET",} 0.0
# HELP vertx_eventbus_processed_total Number of processed messages
# TYPE vertx_eventbus_processed_total counter
vertx_eventbus_processed_total{side="local",} 270000.0
# HELP vertx_http_server_bytes_written_total Number of bytes sent by the server
# TYPE vertx_http_server_bytes_written_total counter
vertx_http_server_bytes_written_total 73114.0
# HELP vertx_eventbus_received_total Number of messages received
# TYPE vertx_eventbus_received_total counter
vertx_eventbus_received_total{side="local",} 610000.0
# HELP vertx_http_server_requests_total Number of processed requests
# TYPE vertx_http_server_requests_total counter
vertx_http_server_requests_total{code="200",method="GET",route="/",} 23.0
# HELP vertx_eventbus_sent_total Number of messages sent (point-to-point)
# TYPE vertx_eventbus_sent_total counter
vertx_eventbus_sent_total{side="local",} 610000.0
# HELP vertx_http_server_active_connections Number of opened connections to the server
# TYPE vertx_http_server_active_connections gauge
vertx_http_server_active_connections 1.0
# HELP vertx_http_server_response_time_seconds_max Request processing time
# TYPE vertx_http_server_response_time_seconds_max gauge
vertx_http_server_response_time_seconds_max{code="200",method="GET",route="/",} 0.0
# HELP vertx_http_server_response_time_seconds Request processing time
# TYPE vertx_http_server_response_time_seconds summary
vertx_http_server_response_time_seconds_count{code="200",method="GET",route="/",} 23.0
vertx_http_server_response_time_seconds_sum{code="200",method="GET",route="/",} 0.051776341
# HELP vertx_eventbus_delivered_total Number of messages delivered to handlers
# TYPE vertx_eventbus_delivered_total counter
vertx_eventbus_delivered_total{side="local",} 360000.0
# HELP vertx_http_server_response_bytes_max Size of responses in bytes
# TYPE vertx_http_server_response_bytes_max gauge
vertx_http_server_response_bytes_max{code="200",method="GET",route="/",} 0.0
# HELP vertx_http_server_response_bytes Size of responses in bytes
# TYPE vertx_http_server_response_bytes summary
vertx_http_server_response_bytes_count{code="200",method="GET",route="/",} 23.0
vertx_http_server_response_bytes_sum{code="200",method="GET",route="/",} 73114.0
# HELP vertx_eventbus_reply_failures_total Number of message reply failures
# TYPE vertx_eventbus_reply_failures_total counter
vertx_eventbus_reply_failures_total 610000.0
# HELP vertx_eventbus_handlers Number of event bus handlers in use
# TYPE vertx_eventbus_handlers gauge
vertx_eventbus_handlers 1.0
```

Thank you.

**Comment by dehypnosis** [comment] 2021-07-20 04:51
do you think should i have to worry about this situation? 🥲

**Comment by vietj** [comment] 2021-07-20 05:36
I will have a look at your code @dehypnosis

**Comment by vietj** [comment] 2021-07-20 05:47
can you provide a reproducer that works locally ?

**Comment by dehypnosis** [comment] 2021-07-21 02:53
@vietj 
Thank you. This code can work locally. I had made it for you. 😃
https://github.com/dehypnosis/vertx-pending-handlers/blob/main/src/main/java/com/kakaomobility/connection/Main.java

**Comment by vietj** [comment] 2021-07-22 09:15
can you open a new issue and link this reproducer ?

**Comment by vietj** [comment] 2021-07-22 10:01
I tried to run it but I don't see where I should look at to the the issue can you elaborate ?
