### ISSUE TITLE
DecodeException used in Json, is missing useful information.

### ISSUE THREAD

**Issue by sorenburon** [eclipse/vert.x#1786] opened 2017-01-30 15:43 UTC
Maybe I overlooked something, but why not use the information that the exceptions from Jackson provides? Especially the JsonMappingException gives useful information about the json format (e.g. missing/invalid params), which is useful feedback to provide consumers of a REST api.

For now it seems,  that I have to manually go through the json object to see if the all the params needed are present and valid for a given endpoint.

It would help a lot if the DecodeException contained easy accessible information about the path to the invalid/missing parameters.

**Comment by tsegismont** [comment] 2017-01-31 15:31
Good question. We may add a constructor to the class, allowing to store the cause. Then you would be able to test if the cause is a JsonMappingException. Fancy a pull request?

**Comment by sorenburon** [comment] 2017-02-02 12:23
👍  https://github.com/eclipse/vert.x/pull/1792

**Comment by vietj** [comment] 2017-03-01 23:37
closing this as it was merged

**Closed by vietj** 2017-03-01 23:37 UTC
