### ISSUE TITLE
HttpServer with compression enabled throws ClosedChannelException when "Connection: Close" in header

### ISSUE THREAD

**Issue by chili1k** [eclipse/vert.x#2214] opened 2017-11-17 15:05 UTC
Affected version: 3.5.0. 3.4.2 seems ok.

Steps to reproduce:

Code:
```        
server = vertx.createHttpServer(new HttpServerOptions()
  // this causes the exception
  .setCompressionSupported(true)
);

router.route()
    .method(HttpMethod.GET)
    .path("/")
    .handler(ctx -> {
        ctx.response().end();
});
```

Issue request with "Connection: Close":

```
curl -H "Connection: close" localhost:8080
curl: (52) Empty reply from server
```

**Comment by vietj** [comment] 2017-11-17 15:15
duplicate of https://github.com/eclipse/vert.x/issues/2184

**Closed by vietj** 2017-11-17 15:15 UTC
