### ISSUE TITLE
HttpClientRequest#write fails to write Buffer returning a ByteBuf with its readerIndex > 0

### ISSUE THREAD

**Issue by TanyaGaleyev** [eclipse/vert.x#1951] opened 2017-04-19 16:30 UTC
We are using code similar to [example](https://github.com/vert-x3/vertx-examples/blob/master/core-examples/src/main/java/io/vertx/example/core/http/proxy/Proxy.java). And IndexOutOfBoundsException was observed. After debugging for a while I found a reason of the problem.
In proxy code we have something like:
```java
public void processRequest(HttpServerRequest request) {
  HttpClientRequest destRequest = ...
  request.handler(destRequest::write);
  ...
}
```
In file `HttpClientRequestImpl` there is a code:
```java
void write(ByteBuf buf, boolean end) {
  ...
  CompositeByteBuf pending;
  ...
  pending.addComponent(buff).writerIndex(pending.writerIndex() + buff.writerIndex());
  ...
}
```
And if `buff` has `readerIndex` not equal to 0 then call to `writerIndex` fails with reasonable IndexOutOfBoundsException.
Current workaround is using `Buffer.slice()` before passing buffer read by http server to http client. But I think that buffers with non 0 `readerIndex` should be handled properly by `HttpClientRequestImpl`.

**Comment by vietj** [comment] 2017-04-19 21:39
can you provide a reproducer ?

**Comment by TanyaGaleyev** [comment] 2017-04-20 11:48
@vietj 
The problem is reproduced in unit test in this [repo](https://github.com/TanyaGaleyev/vertxproxy). It turns out that with plain everything works fine with plain HTTP, but starts failing with HTTPS.

**Comment by vietj** [comment] 2017-04-20 11:55
thanks

**Comment by vietj** [comment] 2017-04-20 13:24
it seems due to this change in Netty : https://github.com/netty/netty/commit/930633350d6b42831bc079675e521ee8f4d4e7e4#diff-7191c076eacd4a1a53d60604a5d2a251R219

previous version of duplicate called by `HttpClientRequestImpl#write(Buffer)` really got a slice and not the duplicate buffer has a `readerIndex > 0` because the original duplicated buffer as an `adjustment > 0`

**Comment by TanyaGaleyev** [comment] 2017-04-20 13:48
Thanks for investigation! What are there the next steps for this issue?
Also I wonder why should we assume that buffer coming to `HttpClientRequestImpl#write(Buffer)` has `readerIndex == 0`? May be one can use:
```java
pending.addComponent(buff).writerIndex(pending.writerIndex() + buff.READABLEBYTES());
```
Or even more use `CompositeByteBuf.addComponent(boolean increaseWriterIndex, ByteBuf buffer)` with `increaseWriterIndex == true`?
Sorry if my suggestions are silly =)

**Comment by vietj** [comment] 2017-04-20 16:17
@TanyaGaleyev actually the buffer we obtain is via `io.vertx.core.buffer.Buffer#getByteBuf()` that returns a duplicate of the buffer with its `readerIndex == 0`... until now.

**Comment by vietj** [comment] 2017-04-20 16:18
I think it will be fixed in 3.4.2 with improvements in `Buffer` class and also a test with a buffer that has readerIndex > 0 for `write` method and a fix.

**Comment by vietj** [comment] 2017-04-20 16:20
`CompositeByteBuf.addComponent(boolean increaseWriterIndex, ByteBuf buffer)` seems like a good fix as you said, we just need to have a corresponding test for it that write a Buffer wrapping a ByteBuf with a `readerIndex > 0` which can be obtained with something like `Buffer.buffer("foobar").slice(3, 6)` I think.

**Comment by vietj** [comment] 2017-04-20 16:57
I pushed a fix based on your suggestion with a test, would you mind to check it's fine on your side ?

**Closed** 2017-04-20 16:57 UTC

**Comment by TanyaGaleyev** [comment] 2017-04-21 16:14
@vietj 
I noticed that there is also another line in `HttpClientRequestImpl` that can be also affected:
```java
cachedChunks.addComponent(buff).writerIndex(cachedChunks.writerIndex() + buff.writerIndex());
```

**Comment by TanyaGaleyev** [comment] 2017-04-21 16:16
@vietj 
I hope to check it in my environment soon. Is there any maven repository where I can take latest dev version?

**Comment by vietj** [comment] 2017-04-21 17:12
good catch, I'll try to make a test for this one.

you can get the snapshots from the Sonatype OSS snapshot repository https://oss.sonatype.org/content/repositories/snapshots/

**Comment by vietj** [comment] 2017-04-22 14:09
@TanyaGaleyev the computation of the content-length needs also to be fixed `headers().set(CONTENT_LENGTH, String.valueOf(buff.writerIndex()));`

**Comment by vietj** [comment] 2017-04-22 14:15
I've those in `HttpClientRequest`

**Comment by TanyaGaleyev** [comment] 2017-04-24 11:25
@vietj 
Thanks for fixes. I checked my production code with 3.4.2-SNAPSHOT, everything works fine.

**Comment by TanyaGaleyev** [comment] 2017-04-24 11:27
When 3.4.2 will be released?

**Comment by vietj** [comment] 2017-04-24 13:14
around May, we aim to start the release process early may and conclude before june

**Comment by vietj** [comment] 2017-04-24 13:14
not saying it's a slow process, just saying that we shall do it peacefully :-)

**Comment by TanyaGaleyev** [comment] 2017-04-24 13:57
Thanks for info.
