### ISSUE TITLE
Expose executeBlocking() with custom executor

### ISSUE THREAD

**Issue by luengnat** [eclipse/vert.x#1650] opened 2016-09-27 17:52 UTC
There should be an overloaded method for executeBlocking() which takes a generic executor. Currently, it is not possible since ContextImpl.setContext is not working non-Vert.x thread. If it is modified to work on non-Vert.x thread, it could expose this functionality. While #1539 could help that, this proposed change makes it much more flexible to use multiple thread pool to perform various tasks where it is quite inflexible with createSharedWorkerExecutor since it has a limited set of configurable parameters. In addition to that, this makes it easier for Vert.x to share worker threads with outside components.

**Comment by vietj** [comment] 2016-09-27 19:25
Hi, it's a duplicate of : https://github.com/eclipse/vert.x/issues/1539

**Closed by vietj** 2016-09-27 19:25 UTC

**Comment by luengnat** [comment] 2016-09-27 22:06
It is not exactly the same. That's why I mentioned #1539. I think it is much simpler to allow any executor to be used without having to create them via createSharedWorkerExecutor.
