### ISSUE TITLE
Add support for error reason (+reason text) in ServerWebsocket::close

### ISSUE THREAD

**Issue by f24-gklein** [eclipse/vert.x#1400] opened 2016-05-03 12:42 UTC
WebSocket spec defines optional reason codes and text when closing a websocket connection: https://tools.ietf.org/html/rfc6455#section-5.5.1
ServerWebSocket however just provides a simple close() method without any parameters (internally Nettys new CloseWebSocketFrame(1000, null) will be called). Also websocket client's closeHandler has no way to access reason data. Please provide support for that, as we need to signal the client the concrete close reason! 
In the meanwhile: Is there any simple way to hook into the close process and override the reason code?

**Comment by almikhayl** [comment] 2016-05-21 22:14
I suppose there are no easy way to hook into, but you can write close frame to websocket and then call close(). After receiving close frame peer ignore all other data from us and following one more close frame with `new CloseWebSocketFrame(1000, null)` will do no harm, but vert.x correctly handle reply close frame from peer.

```
WebSocketFrame closeFrame = new WebSocketFrameImpl(FrameType.CLOSE, Unpooled.copiedBuffer("CloseReason", StandardCharsets.UTF_8));
websocket.writeFrame(closeFrame);
websocket.close();
```

**Comment by f24-gklein** [comment] 2016-06-16 17:24
Unfortunately this does not work for me. I wrote a litte javascript that handles the close event:
`wsocket.onclose = function(event) {
		alert('code=' + event.code + ', reason=' + event.reason);
}
`

This will print out:
`code=1006, reason=`

Am i doing something wrong here?

**Comment by f24-gklein** [comment] 2016-06-28 10:52
Any news on this? Your proposed solution does not work for us. We definitely need a way to notify clients of close reason and reason phrase

**Comment by vietj** [comment] 2016-06-28 11:08
@f24-gklein it looks useful to me, perhaps this is something you can contribute to ?

**Comment by f24-gklein** [comment] 2016-06-29 11:06
@vietj i would love to - let's see if i can find some time;-) Do you have any further information about contributing code, like required setup steps, build process, etc. Or is it just pulling the repo and running the main pom?

**Comment by vietj** [comment] 2016-06-29 13:18
https://github.com/vert-x3/wiki/wiki/How-to-contribute-to-Vert.x

**Comment by vietj** [comment] 2018-04-14 20:28
that was actually implemented recently and this is a duplicate of https://github.com/eclipse/vert.x/issues/2276

**Closed by vietj** 2018-04-14 20:28 UTC
