### ISSUE TITLE
Exception in DefaultChannelPipeline: it reached at the tail of the pipeline

### ISSUE THREAD

**Issue by leolux** [eclipse/vert.x#2368] opened 2018-04-04 10:27 UTC
Today I received a lot of exceptions every millisecond for hours looking like an infinite loop in the log file:

```
2018-04-04 01:16:38,513 [31mWARN[0;39m [vert.x-eventloop-thread-2] [i.n.c.DefaultChannelPipeline] - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. java.lang.IllegalArgumentException: invalid version format: (T H I S  I S   J U S T  A  S U R V E Y !)
	at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:121)
	at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:76)
	at io.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:87)
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:219)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:60)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

1. What does this come from? Does i thappen during request or response handling or during SSL handshake?
2. Where to add a exception handler to catch this exception
3. Where does **T H I S  I S  J U S T  A  S U R V E Y !** come from?

**Comment by pmlopes** [comment] 2018-04-04 10:48
I think the item 3 is because someone is handcrafting the HTTP request with that string instead of the HTTP version, for example when you start the request using a tool like telnet and do:

```
HTTP/THIS IS JUST A SURVEY\n
...
GET /\n
\n
```

**Comment by vietj** [comment] 2018-04-04 10:51
1. it seems to happen on a non TLS connection according to the stack trace (no SslHandler)
2. we do have an HttpServer#exceptionHandler but I think currently it won't catch these messages, the current behavior of Vert.x when this happens is to close the connection, but it could be a good option I think to add it
3. as @pmlopes said

**Comment by micou** [comment] 2018-04-04 10:57
Hello,
It is funny we have been spammed by this during the night.

**Comment by leolux** [comment] 2018-04-04 11:06
Ok, thanks! For me it looks like a DoS attack with a http fuzz. 

@micou What do you mean by "spammed during the night"? Are ther some other victims as well?

**Comment by micou** [comment] 2018-04-04 11:25
Yes we have been victim of a DoS attack :(

**Comment by leolux** [comment] 2018-04-04 12:02
@micou In my case it was on port 80. How to find out where this requests came from? 

@videlalvaro Is it possible to get the source IP for http fuzz attacks?

**Comment by vietj** [comment] 2018-04-04 16:30
I'm closing this issue unless there is a real bug

**Comment by leolux** [comment] 2018-04-04 16:35
Alright, thanks!

**Comment by rbramante** [comment] 2018-05-29 19:43
@vietj I have been able to reproduce this issue using curl if I lie about the Content-Length (report it short) and then insert a new line in the body of the request. e.g.:

```
curl -iv -H "Content-Type: application/json" -H "Content-Length: 6" -d 'a b c d
> ' http://localhost:9992/support/logging/set
```
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9992 (#0)
> POST /support/logging/set HTTP/1.1
> Host: localhost:9992
> User-Agent: curl/7.55.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 6
> 
* upload completely sent off: 8 out of 8 bytes
< HTTP/1.1 400 Bad Request
< Content-Length: 67
< 
* Connection #0 to host localhost left intact

```
The client gets a request of invalid JSON and returns 400 and all looks well from this view. However, vertx is looping tightly reporting the exception:

````
2018-05-23 19:14:19.195 WARN 20 DefaultChannelPipeline An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: text is empty (possibly HTTP/0.9)
    at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:63)
    at io.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:87)
    at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:219)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
````
Is the "last handler in the pipeline did not handle the exception" something my code is supposed to account for or is this something else (our error handling for other cases follows the same pattern without apparent negative results, but for this case we hit this degenerate behavior).

**Comment by vietj** [comment] 2018-05-29 21:44
great will investigate @rbramante

**Comment by vietj** [comment] 2018-05-29 21:45
I think it happens because at this moment the HTTP handler is not set and I believe it should be routed to the HTTP server exception handler

**Comment by vietj** [comment] 2018-05-29 21:45
not a big deal though as it happens at connection time

**Comment by nfranke** [comment] 2018-07-20 16:44
Anything I can do to prevent this? I've got 230 GB of logs in just a few days.

**Comment by vietj** [comment] 2018-07-20 16:52
try to set an exception handler on the server (`HttpServer#exceptionHandler(Handler<Throwable))`) to process the exception

**Comment by nfranke** [comment] 2018-07-23 18:42
I set an exception handler as suggested, but it didn't help.

**Comment by nfranke** [comment] 2018-07-24 20:06
I should clarify. On which object should I set the exceptionHandler? I had the HttpServer and the Router. I just added one to the Vertx instance as well.

**Comment by vietj** [comment] 2018-07-25 13:40
we need to investigate, in the meantime I think you can configure logging for this

**Comment by nfranke** [comment] 2018-07-25 21:40
Not sure how, exactly. Not sure that will help, either, since the entire app becomes responsive when this happens. Event messages pushed to the event bus do not process.

**Comment by nfranke** [comment] 2018-07-25 22:01
Hopefully this helps. I was able to use jstack to dump a stack trace. My EventBus is hung in the app at this point. Servicing web requests does continue to work, however.

```   java.lang.Thread.State: RUNNABLE
	at java.lang.Throwable.getStackTraceElement(Native Method)
	at java.lang.Throwable.getOurStackTrace(Throwable.java:827)
	- locked <0x00000007a5fb8f88> (a java.lang.Throwable)
	at java.lang.Throwable.getStackTrace(Throwable.java:816)
	at io.netty.util.internal.logging.JdkLogger.fillCallerData(JdkLogger.java:619)
	at io.netty.util.internal.logging.JdkLogger.log(JdkLogger.java:605)
	at io.netty.util.internal.logging.JdkLogger.warn(JdkLogger.java:482)
	at io.netty.channel.DefaultChannelPipeline.onUnhandledInboundException(DefaultChannelPipeline.java:1158)
	at io.netty.channel.DefaultChannelPipeline$TailContext.exceptionCaught(DefaultChannelPipeline.java:1241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1326)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:923)
	at io.vertx.core.http.impl.Http1xServerConnection.handleError(Http1xServerConnection.java:409)
	at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:420)
	at io.vertx.core.http.impl.Http1xServerConnection.lambda$checkNextTick$3(Http1xServerConnection.java:489)
	- locked <0x00000006c1030fe0> (a io.vertx.core.http.impl.Http1xServerConnection)
	at io.vertx.core.http.impl.Http1xServerConnection$$Lambda$142/932250444.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.vertx.core.impl.ContextImpl$$Lambda$43/860848518.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chrismichaelscott** [comment] 2018-07-27 14:38
Hi. My company's software has started suffering from this issue and ran up considerable (and expensive) logging.

We have observed that this issue occurs with Vert.x 3.5.1 but is not present in 3.5.2 (at least for us). Same for @rbramante 's test.

I recommend upgrading.

**Comment by vietj** [comment] 2018-07-30 04:56
@chrismichaelscott thanks for clarifying, I remember we indeed fixed issues related and was dubious about the error.

I've run a test and now the exception is not logged anymore and it is also passed to the server exception handler, so the application can be aware of such issue

**Closed by vietj** 2018-07-30 04:56 UTC
