### ISSUE TITLE
Proxy based http connections do not throw Proxy errors

### ISSUE THREAD

**Issue by techpavan** [eclipse/vert.x#1489] opened 2016-07-04 11:13 UTC
Http Client requesting via web proxy does not throw errors from the proxy server.

Discussion: https://groups.google.com/forum/#!topic/vertx/LialiWptlLQ

Reproducer:
```

public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        HttpClientOptions options = new HttpClientOptions();
        ProxyOptions proxyOptions = new ProxyOptions();
        proxyOptions.setHost("www.google.com");
        proxyOptions.setPort(80);
        options.setProxyOptions(proxyOptions);
        HttpClient client = vertx.createHttpClient(options);
       
        client.getAbs("http://vertx.io/", resp ->
            System.out.println(resp.getHeader("Content-Length")))
            .exceptionHandler(e -> System.out.println("Got error: "+e.getMessage()))
            .end();
       
        try {
            new CountDownLatch(2).await();
        } catch (InterruptedException e) {   }
}
```

**Comment by alexlehm** [comment] 2016-07-05 10:47
I have implemented a unit test in vertx-core that reproduces the issue, when the logging in Netty is active, it will give the warning. I have not yet implemented a fix, it looks like there is method for exception missing in ChannelInboundAdapter

**Comment by vietj** [comment] 2016-07-05 10:51
do you intent to fix the bug or should someone else look at it ?

**Comment by alexlehm** [comment] 2016-07-05 10:56
I started checking for the fix last night, but I didn't get it quite finished, I can do it this evening.

**Comment by vietj** [comment] 2016-07-05 11:02
this evening works too!

**Comment by vietj** [comment] 2016-07-05 22:29
fixed by https://github.com/eclipse/vert.x/pull/1497

**Closed by vietj** 2016-07-05 22:29 UTC
