### ISSUE TITLE
Null Pointer returned in ConnectionBase.writeChannel

### ISSUE THREAD

**Issue by kevlarC** [eclipse/vert.x#1347] opened 2016-03-24 10:11 UTC
I've just seen a null-pointer exception when our very simple http server below is serving files. Nothing special.

I traced back the Null Pointer to ConnectionBase.writeChannel
There is a wierd case that is returning a null, can someone suggest a reason this is done and why it would reach this code?
More of a philosophical question, why is the null returned? Surely this means a large amount of null checking and fragile code ?
Maybe there should be an exception?

Note this has not changed in the main branch since 3.2.0

Exception trace:
<code>
 java.lang.NullPointerException: null
        at io.vertx.core.http.impl.HttpServerResponseImpl.doSendFile(HttpServerResponseImpl.java:493) ~[vertx-core-3.2.0.jar:na]
        at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:340) ~[vertx-core-3.2.0.jar:na]
        at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:317) ~[vertx-core-3.2.0.jar:na]
        at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:303) ~[vertx-core-3.2.0.jar:na]
<code>

Note the IP stuff has been taken out for NDA reasons.
<code>
public class Server extends AbstractVerticle {

```
String path="some_path"
@Override
public void start(Future<Void> future) {
    startServer(future);
}

private void startServer(Future<Void> future) {
    vertx.createHttpServer().requestHandler(this::processRequest).listen(8080, result ->  future.complete());
}

private void processRequest(HttpServerRequest req) {

    String file = path + req.path();
    req.response().sendFile(file, res -> {
        if (res.failed()) {
            log.warn("File not found {}", file);
            setErrorResponse(req, file);
        }
    });
}

private void setErrorResponse(HttpServerRequest req, String file) {
    req.response()
       .setStatusCode(404);
    req.response()
       .end("File not found");
}
```

}
<code>

**Comment by vietj** [comment] 2016-03-24 13:46
it seems that would happen because you are sending a file on a close connection.

the channel future could be null checked before and throw an IllegalStateException instead of an NPE

**Comment by kevlarC** [comment] 2016-04-11 13:23
I agree, This should be an exception probably stating the cause.

**Comment by xkr47** [comment] 2016-11-19 21:00
Is this the line `this.channelFuture.addListener((future) -> {` ? At least I just got a NPE from there when the channel was already closed.

**Comment by vietj** [comment] 2018-04-14 20:10
I'm closing this issue as we haven't had a clean reproducer for this and the actual code in ConnectionBase has changed significantly since this was reported.

**Comment by vietj** [comment] 2018-04-14 20:11
reopen if you can reproduce with 3.5.x

**Closed by vietj** 2018-04-14 20:10 UTC
