### ISSUE TITLE
Http client hangs if connection pooling is used (default)

### ISSUE THREAD

**Issue by azhuchkov** [eclipse/vert.x#1244] opened 2015-12-15 10:24 UTC
I'm writing non-blocking HTTP proxy server and faced with the issue: after several benchmark iterations my server stop handling requests. As I see pooled connections are in CLOSE_WAIT state (according to netstat) which means that remote server has closed them, but vert.x http client still keeps them for sending data. I suppose when new request arrives vert.x acquires one of them to pass the request and then hangs.

My environment:
Vert.x 3.1.0
JDK 1.8
OS X 10.9.5

Code sample (Kotlin):
```kotlin
val clientOptions =
                HttpClientOptions()
                        .setDefaultHost("$BUCKET.s3.amazonaws.com")
                        .setMaxPoolSize(1000)

        val client = vertx.createHttpClient(clientOptions)

        val serverOptions =
                HttpServerOptions()
                .setAcceptBacklog(1000)

        vertx.createHttpServer(serverOptions)
                .requestHandler { request ->
                    val path = request.path()

                    when (request.method()) {                        
                        HttpMethod.GET -> {
                            client.get(path) { s3Response ->
                                if (s3Response.statusCode() != 200)
                                    request.response().setStatusCode(s3Response.statusCode()).end()
                                else {
                                    val response =
                                            request.response()
                                                    .putHeader(LENGTH_HEADER, s3Response.getHeader(LENGTH_HEADER))

                                    val pump = Pump.pump(s3Response, response)

                                    s3Response.endHandler { response.end() }

                                    pump.start()
                                }
                            }
                            .putHeader("Date", "...") // put required headers
                            .end()
                        }
                        else ->
                            request.response().setStatusCode(400).end("Unsupported HTTP verb")
                    }
                }
                .listen(8080) { result ->
                    if (result.succeeded())
                        future.complete()
                    else
                        future.fail(result.cause())
                }

...

@JvmStatic fun main(args: Array<String>) {
            Launcher.main(arrayOf("run", MyVerticle::class.java.name))
}
```

The issue looks similar to https://github.com/eclipse/vert.x/issues/1218 but differs in closing connection trigger - my case is a remote server closes connection explicitly. I suppose that http client should close it in order and remove from pool.

**Comment by vietj** [comment] 2015-12-15 10:28
hi, can you provide a "reproducer" that can be executed from the command line, like a gradle or maven project ? also it would be good if you convert this code to java, so we can debug it with Eclipse.

**Comment by vietj** [comment] 2015-12-15 10:29
when you say close: do you mean TCP connection close or connection close header ? it's not clear.

**Comment by azhuchkov** [comment] 2015-12-15 11:59
CLOSE_WAIT state means TCP connection close.

**Comment by vietj** [comment] 2015-12-15 12:13
yes I know that :-)

**Comment by azhuchkov** [comment] 2015-12-15 17:42
Ok, I wrote a simple demo in Java (and attached it to the comment). You can run it from your IDE or using `java -jar target/vertx-http-proxy-demo-1.0-SNAPSHOT-fat.jar` after `mvn clean install`.

Steps to reproduce:
1. run several times Apache Benchmark tool: `ab -n10000 -c100
[vertx-http-proxy-demo.zip](https://github.com/eclipse/vert.x/files/62987/vertx-http-proxy-demo.zip)
0 http://localhost:8080/` (it may fail, but it doesn't affect test results).
2. after that try to do `curl -i http://localhost:8080/`
3. if request hangs you may start investigation :)

And here is my results.

Here is my connections to google server (filtered output from `netstat -anp TCP` report):
```
tcp4       0      0  172.20.208.154.52935   173.194.220.101.443    ESTABLISHED
tcp4       0      0  172.20.208.154.50858   173.194.71.138.443     ESTABLISHED
tcp4     827      0  172.20.208.154.65231   173.194.71.103.80      CLOSE_WAIT
tcp4     827      0  172.20.208.154.65230   173.194.71.103.80      CLOSE_WAIT
tcp4     827      0  172.20.208.154.65229   173.194.71.103.80      CLOSE_WAIT
tcp4     827      0  172.20.208.154.65228   173.194.71.103.80      CLOSE_WAIT
tcp4     827      0  172.20.208.154.64215   173.194.71.104.80      CLOSE_WAIT
tcp4       0      0  172.20.208.154.64143   173.194.122.239.443    ESTABLISHED
```

What my `ping www.google.com` shows (to be sure I'm not confusing these connections with something else):
```
PING www.google.com (173.194.71.104): 56 data bytes
64 bytes from 173.194.71.104: icmp_seq=0 ttl=50 time=18.111 ms
```
Here you can see that 3 of them are in `ESTABLISHED` state and are using `HTTPS` (port 443). I suppose they are established by browser. And 5 of them are in `CLOSE_WAIT` state and have non-empty `Recv-Q` (827 bytes). Apparently they are connections from the http client pool (5 is a default pool size).
 
In this state proxy server stops handling incoming requests. Even simple `curl http://localhost:8080/` hangs.

After stopping process I can see tons of such errors:
```
io.vertx.core.VertxException: Connection was closed
	at io.vertx.core.http.impl.ClientConnection.handleClosed(ClientConnection.java:305)
	at io.vertx.core.net.impl.VertxHandler$$Lambda$48/554857636.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl$$Lambda$22/1525262377.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:218)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:204)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:332)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:212)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:132)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:218)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:204)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:625)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
```
Such records are interlaced with: `java.nio.channels.ClosedChannelException`

**Comment by vietj** [comment] 2015-12-15 19:13
is "www.google.com" as host good for reproducing ? I see it can be another value according to conf.

**Comment by vietj** [comment] 2015-12-15 19:13
have you tried with 3.0 ?

**Comment by vietj** [comment] 2015-12-15 19:45
when running this with google.com with the same settings all my connection are established, I don't have any connection.

a curl on localhost:8080 hangs which is normal as the http server of the proxy is very busy since many requests are queued in the client connection manager. after a little while it is served.

**Comment by alexlehm** [comment] 2015-12-15 20:21
I think I know how to reproduce that with a local server, I will try to write a sample test later

**Comment by azhuchkov** [comment] 2015-12-15 20:40
@vietj I faced with this issue when was testing against Amazon S3. Last time I did it I got CLOSE_WAIT connections quite quickly. Just made pool size = 1000 and started benchmark with 1000 concurrent requests - netstat showed me lots of CLOSE_WAIT connections to Amazon server right away. Test against `www.google.com` showed them later - I suppose it's necessary to wait some time or make more benchmark runs. I don't believe it's environment issue, because CLOSE_WAIT means that __local__  process didn't acknowledge connection close. I think they shouldn't hang in this state anyways. 

@alexlehm Please share your thoughts :) Maybe I can do something with it.

**Comment by alexlehm** [comment] 2015-12-15 21:00
@azhuchkov I assume that the amazon s3 server supports keep-alive, but will close the connection at some point (apache is configured to close the connection after 100 keep-alive requests, maybe that is similar), so the sequence of requests is working until the connection is closed by the server, but the vert.x client thinks that the connection is still available, the 2nd possibility is that the connection times out after a few seconds and this is not recognized by vert.x.

I cannot directly reproduce that since I don't have access to an aws store, but I think it should be easy to write a test server that replies to a few requests and then closes the connection.

question on the side, would you consider joining the irc for vert.x? this might be easier to chat about the issue (http://vertx.io/community/)

**Comment by vietj** [comment] 2015-12-15 22:43
@alexlehm if you exhibit a reproducer it would be great, and if it can be in the testsuite, even better.

**Comment by alexlehm** [comment] 2015-12-15 22:55
I have created a unit test, but it's not quite finished yet
https://gist.github.com/alexlehm/27fba9235d6eb83a897e

**Comment by vietj** [comment] 2015-12-15 23:00
could you make it not use vert.x unit ? Vert.x Core does not support it so you would need to use core async test constructs, it would be more convenient.

**Comment by alexlehm** [comment] 2015-12-15 23:49
Started rewriting the test, its not quite working, I will continue tomorrow

**Comment by azhuchkov** [comment] 2015-12-16 07:31
@vietj Probably you are right - when server is very busy by doing something it can keep pool connections in half-closed state. But what he is doing and what queues are full and can i see their state in JMX metrics? By the way i run `curl` only while there is no benchmark running, otherwise it would be obvious that server is just busy.

**Comment by vietj** [comment] 2015-12-16 08:25
@azhuchkov I created this issue yesterday for monitoring HttpClient queuing https://github.com/eclipse/vert.x/issues/1245

**Comment by azhuchkov** [comment] 2015-12-16 12:44
Update (`ConnectionManager.connQueues` snapshot):
![ConnectionManager.connQueues state]
(https://www.dropbox.com/s/c72u04q51tfc19p/Screenshot%202015-12-16%2015.30.49.png?raw=1)
It's a state when my server stops handling requests. Here you can see that there is no available connections, `connCount == 200 (maxPoolSize)` and it prevents from creating new connections. All incoming requests just goes into `waiters` queue. Meanwhile netstat shows only one connection to server I proxy requests to and it's in `CLOSE_WAIT` state for a long time.

**Comment by alexlehm** [comment] 2015-12-16 21:02
I have created a project that reproduces the cause of the issue (I hope)

https://github.com/alexlehm/vertx-issue-keepalive

**Comment by azhuchkov** [comment] 2015-12-16 22:14
Some comments to my previous image: `connCount` which prevents new connections creation can be decreased only in `connectionClosed()` method, which according to its comment:
>    Called if the connection is actually closed, OR the connection attempt failed - in the latter case
>    conn will be null

And actually it used this way. But what if we have any other kind of failure, e.g. connection reset on `read` or `write` attempt? Would a connection be removed from the pool some time or stick there forever?

**Comment by vietj** [comment] 2015-12-16 23:19
thanks @alexlehm will have a look

**Comment by vietj** [comment] 2015-12-16 23:38
@alexlehm reproducer clearly shows the requests hanging when all ClientConnection have been closed, however it is not related to CLOSE_WAIT.

**Comment by vietj** [comment] 2015-12-17 00:32
@azhuchkov can you try this branch https://github.com/eclipse/vert.x/tree/connection-close-fix to see how it goes ?

**Comment by vietj** [comment] 2015-12-17 00:39
actually it is not sure it is related to @azhuchkov . @azhuchkov can you give us the http response details (status+headers) of your "$BUCKET.s3.amazonaws.com" server  ?

**Comment by vietj** [comment] 2015-12-17 07:42
@alexlehm you test is relevant, but what it shows imho is not this issue.

It shows that when a connection is closed by the server and keepalive==true, then a waiter can use this connection and will receiver an error on the request exceptionHandle since the connection is closed. The connection_close_fix branch fixes this problem and close the connection on the client therefore the queued requests will not use this connection and will likely succeed.

According to @azhuchkov the problem seems to happen at the TCP level and the connections to the host remains unclosed in the pool stopping the queue from being served because the vertx client connection does not get closed.

So to observe this we need a reproducer that shows client connection closed by the server but not on the client. This seems to be the source of the problem.

**Comment by vietj** [comment] 2015-12-17 07:46
@azhuchkov on a connection error, it will be removed from the pool, your problem seems to be that the connection remains unclosed and it blocks the waiters to get a new connection. See my previous comment.

**Comment by azhuchkov** [comment] 2015-12-17 07:58
@vietj on a connection (meaning `CONNECT` operation) error - yes, it would be removed from the pool. But what happen if connection attempt succeeds and then connection reset raised on e.g. reading operation? I suspect this failure doesn't eventually call `ConnQueue.connectionClosed()` and this will exhaust the pool, since only this method removes connections from the pool (if we do not consider `ConnectionManager.close()`).

Will try your fix later. Thanks!

**Comment by azhuchkov** [comment] 2015-12-17 08:07
Amazon S3 normally (without requests pressure) do not send headers like `Connection` and `Keep-Alive`. According to specs, HTTP 1.1 doesn't require them - server just keeps connection open by default. 

Snapshots from `tcpdump`:
```
GET /azhuchkov/gradlew HTTP/1.1
Date: Thu, 17 Dec 2015 11:03:20 +0300
Authorization: AWS AKIAJ7KCJ553V4Y5QA:=
Host: test.s3.amazonaws.com

HTTP/1.1 200 OK
x-amz-id-2: gerpS+XW7nh3dVMiB3ncF+BvpTZRSC1ddLurfELhvsU0H3zYz5rdCFghsJM4Nzo=
x-amz-request-id: 630834CF9E568
Date: Thu, 17 Dec 2015 07:45:24 GMT
Last-Modified: Tue, 15 Dec 2015 13:22:52 GMT
ETag: "a670520d9d36833b3e28d1e4b73cbe22"
Accept-Ranges: bytes
Content-Type: application/octet-stream
Content-Length: 5080
Server: AmazonS3

...content goes here...
```

**Comment by alexlehm** [comment] 2015-12-17 08:57
@azhuchkov yes, you're right (when I wrote the test yesterday I didn't notice that, I have removed the header for keep-alive now)

When executing a HTTP/1.0 request, the Connection: header is present, with HTTP/1.1 it is implicit if no header is present.
When I run a string of requests on the s3 url with HTTP/1.1, the connection is closed after about 80 requests without a Connection: close header, maybe that is causing issues

**Comment by azhuchkov** [comment] 2015-12-17 16:18
I tried the branch with a fix and unfortunately it didn't help to me. 
Here is my updated reproducer: https://gist.github.com/azhuchkov/155dbd132f57c37dc15d. I've found and fixed a bug there (proxied request should be fired on client request end), but the issue is still reproducible.

Steps:
1. run it
2. `ab -n2 -c2 http://localhost:8080/`
3. you should get `Benchmarking localhost (be patient)...apr_socket_recv: Connection reset by peer (54)`
4. `curl -i http://localhost:8080/` is hanging now.

Notes: 
The main purpose is to get connection reset report from `ab` (not a timeout, send failure or something else). I assume that in this case `ab` terminates its connections abruptly. Almost every time I have hanging proxy server after this. But a couple of times it continued working. So, try more times if it doesn't behaves this way the first time. You can change timeouts if it doesn't work in your environment at all. Also I set accept backlog to 1 and connect timeout to 100. As I see the less timeout is set, the earlier you get CLOSE_WAIT state.

Questions:
1. Is it necessary to close resources from `exceptionHandler`?
2. Is it necessary to start a Pump AFTER assigning endHandler? It seems that start method just assigns handler and it's not obvious does order of assignments matter or not. Moreover i've seen both of the examples in Vertex core documentation.
3. Does my reproducer behaves correctly now? I checked against https://github.com/vert-x/vertx-examples/blob/master/src/raw/java/proxy/ProxyServer.java

**Comment by vietj** [comment] 2015-12-17 18:02
@azhuchkov in your code you have `request` that is the `HttpServerRequest`  set an `exceptionHandler` on it and also on the `HttpServerResponse`.

in the HttpServerRequest exception handler -> end() the `proxyRequest`
in the HttpServerResponse exception handler:
1/ stop the pump() for the response
2/ set an handler on the HttpServerResponse
3/ call HttpServerResponse.resume();

here is the explanation : the main difference between your code and the Vert.x proxy example are the pump. The problem might happen when a client of the proxy fails (it will trigger an exception handler either on the request or the response) and the Pump has `paused` the HttpServerResponse. If the response is `paused` and the server has closed the connection. This can lead to the CLOSE_WAIT `HttpClientRequest` you are seing.

**Comment by azhuchkov** [comment] 2015-12-18 07:20
Thank you @vietj. It seems that replacing pump with simple handler solves the issue. But i still cannot make it work with the pump. I added 4 exception handlers to each request/response and no one is called in situation described previously. There are no errors in stdout/stderr as well. See updated gist: https://gist.github.com/azhuchkov/155dbd132f57c37dc15d

**Comment by vietj** [comment] 2015-12-18 08:34
can we talk about that on the vertx group ? you will get more help there and then we can close this issue.

**Comment by testn** [comment] 2016-01-04 18:50
there should probably be an option to make a request/response that has an exception thrown to be cleaned up automatically i.e. making sure that 
- `HttpClientResponse` is `resume()`, `HttpClientRequest` is `end()` on the client side 
- `HttpServerRequest` is `resume()`, `HttpServerResponse` is `end()` on the server side

**Closed** 2016-01-13 12:33 UTC
