### ISSUE TITLE
Error 'Unable to create Channel from...' on 3.5.0

### ISSUE THREAD

**Issue by gogo2** [eclipse/vert.x#2195] opened 2017-10-31 19:40 UTC
After bumping up to Vert.x 3.5.0 I get this error when http server is starting:

`2017-10-31 20:31:40 [vert.x-eventloop-thread-1] [ERROR] Server - Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel`

Any ideas what could've gone wrong?
`

**Comment by zyclonite** [comment] 2017-11-02 12:53
maybe related...

the follwing error happens only on osx
jdk version: 8u152 (oracle)
```
[WARN] i.n.c.n.NioEventLoop - Unexpected exception in the selector loop. 
java.io.IOException: Invalid argument
    at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
    at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
    at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
    at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
    at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
    at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
    at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:748)
```

this does not happen on linux with openjdk 1.8.0_144

**Comment by vietj** [comment] 2017-11-02 12:59
can you provide a project that reproduces that ? it seems to be a Netty issue

**Comment by zyclonite** [comment] 2017-11-02 14:24
i'll try to get you more details later, i do not have a mac at work

**Comment by zyclonite** [comment] 2017-11-03 23:38
took me a while... it does not seem related to the initial exception from gogo2...

but i found a way to trigger my exception from above, it was related to a timer event from vertx which can not be processed by the netty eventloop

try the following code on osx
```
  @Test
  public void test10yTimer(final TestContext ctx) {
    final Async async = ctx.async();
    final Vertx vertx = Vertx.vertx();
    vertx.setTimer(1000 * 60 * 60 * 24 * 365 * 10L, t -> {
      logger.info("10y timer");
      async.complete();
    });
  }
```

on my machine the trigger is around 100_000_001_005L milliseconds delay

**Comment by zyclonite** [comment] 2017-11-03 23:58
on a linux machine the limit is at around 300 years delay

```
  @Test
  public void test300yTimer(final TestContext ctx) {
    final Async async = ctx.async();
    final Vertx vertx = Vertx.vertx();
    vertx.setTimer(1000L * 60 * 60 * 24 * 365 * 300, t -> {
      async.complete();
    });
  }
```
the timer immediately triggers without any error or exception

**Comment by zyclonite** [comment] 2017-11-04 00:17
seems to be different, not httpserver related - i created a new issue for it https://github.com/eclipse/vert.x/issues/2201

**Comment by vietj** [comment] 2017-11-04 02:03
can we close this issue ?

**Comment by zyclonite** [comment] 2017-11-04 09:02
if there is no more input from gogo2, i guess yes

**Closed** 2017-12-06 20:33 UTC
Labels: Invalid
