### ISSUE TITLE
Vertx HttpClient - Wait queue does not empty after timeouts

### ISSUE THREAD

**Issue by kpachar** [eclipse/vert.x#1842] opened 2017-02-27 09:04 UTC
Hello,
If you create a `HttpClient` with the `maxWaitQueueSize` set to a positive number,
and then
if the wait queue fills up, (`poolSize` for the `HttpClient` is also a fixed number)
and then
if, subsequently, one or more of the `HttpClientRequest`s being executed in the pool time-out, owing to no response from the server after their set `timeout` value, I see a strange behavior that all subsequent requests will receive a "Connection pool reached max wait queue size"

Here is a small standalone reproducer:
https://github.com/kpachar/other-issues

Thanks..

**Comment by vietj** [comment] 2017-02-27 09:10
thanks for reporting this

**Comment by vietj** [comment] 2017-02-27 09:36
make sure in your tests you really have a timeout, currently setting a timeout on the HttpClientRequest will not apply if you receive a response (the timer is cancelled when the response is received). You should call setTimeout on the request when you receive the response

**Comment by kpachar** [comment] 2017-02-27 10:20
Thanks! That was the problem. I wasn't aware of the timer getting cancelled if a response is received.

**Comment by kpachar** [comment] 2017-02-27 12:27
Actually, there still is a problem --
     If a request times out while it is still waiting in the wait queue, it is not evicted from the wait queue and becomes something of a zombie that occupies the wait queue but never runs.

Additionally, if the wait queue is exhausted because of these zombies, new requests are not entertained, even if the actual thread pool is empty.

I've updated the reproducer project to show this.
https://github.com/kpachar/other-issues

This is the output I get when I run it:
```
2017-02-27 17:52:22,043 INFO  [vert.x-eventloop-thread-1] Server - Server started on port 8282
2017-02-27 17:52:22,142 INFO  [vert.x-eventloop-thread-1] Server - Got request GET http://localhost:8282/
2017-02-27 17:52:22,146 INFO  [vert.x-eventloop-thread-1] Server - Not ending the response, so that the client is left waiting.
2017-02-27 17:52:22,148 INFO  [vert.x-eventloop-thread-1] Client - Request 1 request recieved response.
2017-02-27 17:52:28,082 INFO  [vert.x-eventloop-thread-2] Client - Request 2 saw exception The timeout period of 5000ms has been exceeded
2017-02-27 17:52:28,085 INFO  [vert.x-eventloop-thread-4] Client - Request 4 saw exception The timeout period of 5000ms has been exceeded
2017-02-27 17:52:28,085 INFO  [vert.x-eventloop-thread-3] Client - Request 3 saw exception The timeout period of 5000ms has been exceeded
2017-02-27 17:52:33,085 INFO  [main] Client - by this time, you should have seen three timeout exceptions in the logs above, thereby freeing up all three slots in the wait queue
2017-02-27 17:52:33,085 INFO  [main] Client - Sending a new request. This should not get a connection-wait-queue-size-maxed out exception
2017-02-27 17:52:33,086 INFO  [main] Client - Request 5 saw exception Connection pool reached max wait queue size of 3
2017-02-27 17:52:37,149 INFO  [vert.x-eventloop-thread-1] Client - Request 1 saw exception The timeout period of 15000ms has been exceeded
2017-02-27 17:53:03,086 INFO  [main] Client - by this time, the connection pool should be free. This request should go through
2017-02-27 17:53:03,087 INFO  [main] Client - Request 6 saw exception Connection pool reached max wait queue size of 3
```

**Comment by vietj** [comment] 2017-02-27 13:17
thanks I'll investigate

**Comment by vietj** [comment] 2017-02-27 18:39
I think your test is still wrong : the connection does not go back to the pool because the server does not close it. This connection should be eventually _resumed_ : either the server send back some data (after let's say 1 second) or the client is configured to with `HttpClientOptions#setIdleTimeout`, or an intermediary closes it. So at some point the channel will become inactive and at this moment, the client react to this event and continue processing the queued requests.

Can you update you test to have the server to handle this behavior ?

**Comment by kpachar** [comment] 2017-02-28 06:29
Thanks, I tried the `HttpClientOptions#setIdleTimeout`, but it does not release the connection, and the wait queue remains busy even after its occupants have timed out.
https://github.com/kpachar/other-issues/blob/idletimeout/src/com/example/vertxtest/client/Client.java

However, in the output, a weird exception indicating some 13ms timeout appears, although this 13ms is not set anywhere. (it's not always 13ms, but just a small number (4ms, 8ms etc) if I run this multiple times)
```
2017-02-28 11:34:43,884 INFO  [vert.x-eventloop-thread-1] Server - Server started on port 8282
2017-02-28 11:34:43,984 INFO  [vert.x-eventloop-thread-1] Server - Got request GET http://localhost:8282/
2017-02-28 11:34:43,989 INFO  [vert.x-eventloop-thread-1] Server - Not ending the response, so that the client is left waiting.
2017-02-28 11:34:43,990 INFO  [vert.x-eventloop-thread-1] Client - Request 1 request recieved response.
2017-02-28 11:34:49,923 INFO  [vert.x-eventloop-thread-2] Client - Request 2 saw exception The timeout period of 5000ms has been exceeded
2017-02-28 11:34:49,926 INFO  [vert.x-eventloop-thread-4] Client - Request 4 saw exception The timeout period of 5000ms has been exceeded
2017-02-28 11:34:49,926 INFO  [vert.x-eventloop-thread-3] Client - Request 3 saw exception The timeout period of 5000ms has been exceeded
2017-02-28 11:34:54,918 INFO  [main] Client - by this time, you should have seen three timeout exceptions in the logs above, thereby freeing up all three slots in the wait queue
2017-02-28 11:34:54,919 INFO  [main] Client - Sending a new request. This should not get a connection-wait-queue-size-maxed out exception
2017-02-28 11:34:54,920 INFO  [main] Client - Request 5 saw exception Connection pool reached max wait queue size of 3
2017-02-28 11:34:58,992 INFO  [vert.x-eventloop-thread-1] Client - Request 1 saw exception The timeout period of 13ms has been exceeded
2017-02-28 11:35:24,876 INFO  [main] Client - by this time, the connection pool should be free. This request should go through
2017-02-28 11:35:24,877 INFO  [main] Client - Request 6 saw exception Connection pool reached max wait queue size of 3
```

Closing the server does indeed free up the connection and the wait queue. However, in the actual problem which this test case tries to model, the server is not in control, and the network between the client and the server can become extremely starved of bandwidth, and no intermediary will close the connection. So the client needs to wiggle out of the situation if the connection is too slow or the server is not responsive enough.

**Comment by kpachar** [comment] 2017-02-28 07:53
In the exception handler that gets notified of the timeout expiry, I can get hold of the connection from the request and close it. Doing so seems to free up the connection, and looks like a workaround. Is this safe to do?  i.e., `request.connection().close();` in the exception handler?

Is there a possibility that by the time the `close()` in the exception handler gets called, the connection could have gotten closed in the interim by some other mechanism (eg: server closing the connection), and Vert.x could have allocated the connection to another request, thereby causing this explicit `close` in the exception handler to close the connection that the newly-allocated request is using?

**Comment by vietj** [comment] 2017-02-28 07:56
yes it is possible (but not recommended), the role of the timeout is not to close the connection but to allow the code that sent the request to take an initiative to do something else

yes that's possible that the connection is used with HTTP/2 (there you should not close the connection at all) or with pipelining - with keep-alive I'm not sure or it be an very edgy case

I would recommend to setup an idle timeout on the client for such cases.

**Comment by vietj** [comment] 2017-02-28 07:58
I will verify that idle timeout does it job with respect to the wait queue.

**Comment by vietj** [comment] 2017-02-28 08:27
@kpachar keep in mind also that when a connection reaches its max amount of connection and a connection is rejected, it will not be executed and is simply discarded.

So it is possible in your test that a request is simply discarded.

_

**Comment by vietj** [comment] 2017-03-01 23:34
any news about your investigation ? I'm closing this issue, please reopen a more specific issue if needed

**Closed by vietj** 2017-03-01 23:34 UTC

**Comment by kpachar** [comment] 2017-03-02 06:28
@vietj Actually I didn't quite understand your comment that said "connection reaches its max amount of connection and a connection is rejected".

**Comment by vietj** [comment] 2017-03-02 09:22
@kpachar when maxWaitQueueSize is reached the connection is not sent by Vertx HttpClient so you should not have a low value like 3 or 2. It should rather be large.

**Comment by kpachar** [comment] 2017-03-02 10:16
@vietj Thanks.

In the interest of documenting the gist of this discussion:
a) The idleTimeout is seconds, not milliseconds, but the timeout is in milliseconds (I should have looked at the javadoc more carefully for that)
b) In case a request waiting in the wait queue sees a timeout, it does not get evicted from the wait queue to make way for other requests to wait,  until the connection pool is full. Therefore, the wait queue size, if explicitly set, should be set to a sufficiently large value.
c) The timeout on a request gets cancelled as soon as the client receives any data.
d) Upon expiration of the timeout, the underlying connection is not automatically closed.

**Comment by vietj** [comment] 2017-03-02 10:59
@kpachar 

a) : yes
b) : yes indeed you are right but as said earlier, the max wait queue size is -1 by default should be large
d) : indeed there can be other requests depending on this connection (pipelined)

**Comment by gsson** [comment] 2017-12-04 14:16
I had an application level need to detect and respond to timeouts (ultimately closing the connection). 

I ran into this exact issue, and my expectation would be that `reset()` would either clean up any resources associated with this request (such as wait queue entries) or indicate a failure to do so.

Using `setIdleTimeout` didn't quite do it since it throws a very generic `VertxException` with a "Connection was closed" message and so, the cause of the error can not easily be identified and recorded.

As a workaround I am now using `setTimeout()` + `connection.close()`, but I wish there was a friendlier way of going about this. Personally not doing pipelining atm, but if this issue occurs it's considered reasonable to lose/retry requests in flight.

**Comment by vietj** [comment] 2017-12-05 10:07
@gsson can you provide a small snippet of code that shows you use case ? (or even a reproducer).

the actual `reset()` for HTTP/1 is flaky and I would like to improve it.

**Comment by gsson** [comment] 2017-12-05 16:15
It's not pretty, and you have to manually kill it, but it consistently gives me 1-2 `ConnectionPoolTooBusyException` per run; https://gist.github.com/gsson/ac6f8ad3c37dbb4544601f4e3c3b6edf

Output is something like:
```Accepting connections on 0.0.0.0/0.0.0.0:51243
Created request io.vertx.core.http.impl.HttpClientRequestImpl@536aaa8d
Got exception java.util.concurrent.TimeoutException: The timeout period of 1000ms has been exceeded while executing GET / for host 0.0.0.0 on io.vertx.core.http.impl.HttpClientRequestImpl@536aaa8d
Resetting connection
Created request io.vertx.core.http.impl.HttpClientRequestImpl@62fdb4a6
Accepted sockets: 1
Got exception java.util.concurrent.TimeoutException: The timeout period of 1000ms has been exceeded while executing GET / for host 0.0.0.0 on io.vertx.core.http.impl.HttpClientRequestImpl@62fdb4a6
Resetting connection
Created request io.vertx.core.http.impl.HttpClientRequestImpl@31206beb
Got exception java.util.concurrent.TimeoutException: The timeout period of 1000ms has been exceeded while executing GET / for host 0.0.0.0 on io.vertx.core.http.impl.HttpClientRequestImpl@31206beb
Resetting connection
Created request io.vertx.core.http.impl.HttpClientRequestImpl@23bb8443
Got exception java.util.concurrent.TimeoutException: The timeout period of 1000ms has been exceeded while executing GET / for host 0.0.0.0 on io.vertx.core.http.impl.HttpClientRequestImpl@23bb8443
Resetting connection
Created request io.vertx.core.http.impl.HttpClientRequestImpl@4ba2ca36
Got exception java.util.concurrent.TimeoutException: The timeout period of 1000ms has been exceeded while executing GET / for host 0.0.0.0 on io.vertx.core.http.impl.HttpClientRequestImpl@4ba2ca36
Resetting connection
Created request io.vertx.core.http.impl.HttpClientRequestImpl@6a79c292
Got exception io.vertx.core.http.ConnectionPoolTooBusyException: Connection pool reached max wait queue size of 3 on io.vertx.core.http.impl.HttpClientRequestImpl@6a79c292
Resetting connection
Got exception io.vertx.core.VertxException: Connection was closed on io.vertx.core.http.impl.HttpClientRequestImpl@62fdb4a6
Resetting connection
```

**Comment by vietj** [comment] 2017-12-05 19:46
I will give it a spin

**Comment by gsson** [comment] 2017-12-19 21:02
@vietj: Getting it to work?

**Comment by chatmachine** [comment] 2018-02-24 07:38
Is there any clean solution which you hit because Connection.reset() is not conclusive with http1.0

**Comment by barbarosalp** [comment] 2020-10-05 17:32
Hi @vietj @kpachar, what is considered to be a large value for `the max wait queue size`?
