### ISSUE TITLE
Regression in Vert.x 3.3.x: when stopping Vert.x, the eventbus shutdown logs an error

### ISSUE THREAD

**Issue by peterhendriks** [eclipse/vert.x#1658] opened 2016-10-03 12:07 UTC
When upgrading from Vert.x 3.2.0 to 3.3.3, we've been noticing that the following error is logged when shutting down Vert.x:

```
io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.IllegalStateException: Result is already complete: succeeded
	at io.vertx.core.impl.FutureImpl.checkComplete(FutureImpl.java:164)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:108)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$callCompletionHandlerAsync$2(EventBusImpl.java:340)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

This happens when Vert.x is shut down, and an event bus has been started. When the event bus is stopped manually before shutting down Vert.x, the error is not thrown. The following test shows this difference in error logging only:

```java
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Future;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonObject;
import org.junit.Test;

public class VertxCloseTest {

    @Test
    public void startStopTestWithEventbusLogsError() {
        startStopTest(TestVerticle.class);
    }

    @Test
    public void startStopTestWithEventbusClosedManuallyDoesNotLogError() {
        startStopTest(TestStopsEventBusVerticle.class);
    }
    
    private void startStopTest(Class<?> verticleClass) {
        Vertx vertx = Vertx.vertx();
        vertx.deployVerticle(verticleClass.getName());
        try {
            Thread.sleep(500L);
        } catch (InterruptedException e) {
            throw new IllegalStateException(e);
        }
        vertx.close();
        try {
            Thread.sleep(500L);
        } catch (InterruptedException e) {
            throw new IllegalStateException(e);
        }
    }

    public static class TestVerticle extends AbstractVerticle {

        @Override
        public void start() {
            getVertx().eventBus().<JsonObject>consumer("test", message -> System.out.println("Hello: " + message));
        }
    }

    public static class TestStopsEventBusVerticle extends AbstractVerticle {

        @Override
        public void start() {
            getVertx().eventBus().<JsonObject>consumer("test", message -> System.out.println("Hello: " + message));
        }

        @Override
        public void stop(Future<Void> stopFuture) throws Exception {
            getVertx().eventBus().close(handler -> {
                System.out.println("close event bus manually");
                stopFuture.complete(null);
            });
        }
    }
}
```
We are not sure what part of the code triggers the error, but it is introduced somewhere between 3.2.1 (does not occur) and 3.3.0 (first version when problem occurs).

**Comment by vietj** [comment] 2016-10-03 12:17
can you check it is not a duplicate of https://github.com/eclipse/vert.x/issues/1625 ?

**Comment by peterhendriks** [comment] 2016-10-03 12:26
That indeed is the same defect, sorry for the duplicate. We will try to work around it for now.

**Comment by vietj** [comment] 2016-10-03 14:17
yes, beside logging, there is no dangerous side effect.

**Closed** 2016-10-12 08:30 UTC

**Comment by vietj** [comment] 2017-02-06 07:55
duplicate
