### ISSUE TITLE
3.5.0 NullPointerException

### ISSUE THREAD

**Issue by st-h** [eclipse/vert.x#2231] opened 2017-11-30 19:01 UTC
While running some tests, I randomly came across this exception:

```
Unhandled exception 
java.lang.NullPointerException
	at io.vertx.core.http.impl.ServerConnection.handleChunk(ServerConnection.java:298)
	at io.vertx.core.http.impl.ServerConnection.handleContent(ServerConnection.java:465)
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:449)
	at io.vertx.core.http.impl.ServerConnection.lambda$checkNextTick$3(ServerConnection.java:506)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

According to [this](https://groups.google.com/forum/#!topic/vertx/7EPAUv73CtY) discussion this is caused by `that happens when Vert.x is closed and still accepting requests (it cannot process)`

**Comment by vietj** [comment] 2017-12-06 20:32
can you tell how to reproduce this issue ?

**Comment by st-h** [comment] 2017-12-06 20:39
Sorry, not really. They just appeared a few times when I was trying to reproduce those weird race conditions when testing #2230 . I just mentioned this over in the google thread as I thought this might be helpful with the issue.

**Comment by vietj** [comment] 2018-01-30 10:10
I will close this for now, since 2230 has been fixed and the code has been fixed to remove race conditions

**Closed by vietj** 2018-01-30 10:10 UTC
